#!/bin/bash
# CW Finance - Build Deployment Package (macOS/Linux)
# 用法: bash scripts/build-deploy.sh

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY="deploy-final"
NODE_VER="20.18.3"

echo ""
echo "========================================"
echo "  CW Finance - Build Deployment Package"
echo "========================================"
echo ""

echo "[1/5] Building frontend (Vite - deploy mode, skip type check) ..."
cd "$ROOT/client"
npx vite build
echo "      OK"
echo ""

echo "[2/5] Building backend bundle (esbuild) ..."
cd "$ROOT/server"
node scripts/buildBundle.mjs
echo "      OK"
echo ""

echo "[3/5] Preparing deploy directory ..."
cd "$ROOT"
rm -rf "$DEPLOY/client/dist"
mkdir -p "$DEPLOY/client/dist"
mkdir -p "$DEPLOY/server"
mkdir -p "$DEPLOY/data"
mkdir -p "$DEPLOY/uploads"
echo "      OK"
echo ""

echo "[4/5] Copying files ..."
# 前端构建产物
cp -R client/dist/* "$DEPLOY/client/dist/"
# 后端 bundle
cp server/dist/bundle.cjs "$DEPLOY/server/bundle.cjs"
cp server/src/db/schema.sql "$DEPLOY/server/schema.sql"
# server config
cp server/package.json "$DEPLOY/server/package.json"
[ -f server/package-lock.json ] && cp server/package-lock.json "$DEPLOY/server/package-lock.json"
# .env
cat > "$DEPLOY/server/.env" << 'ENVEOF'
# Deployment .env - generated by build script
# JWT Secret - change to a strong random string in production
JWT_SECRET=your-s...tion
ENVEOF
# 数据库（如果存在）
if [ -f data/finance.db ]; then
  if [ "${INCLUDE_SAMPLE_DB:-0}" = "1" ]; then
    cp data/finance.db "$DEPLOY/data/finance.db"
    echo "      Sample database copied: data/finance.db"
  else
    echo "      Clean package: no database copied. Set INCLUDE_SAMPLE_DB=1 to include data/finance.db."
  fi
else
  if [ "${INCLUDE_SAMPLE_DB:-0}" = "1" ]; then
    echo "      INCLUDE_SAMPLE_DB=1 but data/finance.db was not found"
  else
    echo "      Clean package: no database copied. Set INCLUDE_SAMPLE_DB=1 to include data/finance.db."
  fi
fi
# 标准模版
if [ -d "标准模版" ]; then
  mkdir -p "$DEPLOY/标准模版"
  cp -r 标准模版/* "$DEPLOY/标准模版/"
fi

# 旧版模版目录（兼容历史部署）
if [ -d "模版" ]; then
  mkdir -p "$DEPLOY/模版"
  cp -r 模版/* "$DEPLOY/模版/" 2>/dev/null || true
fi
echo "      OK"
echo ""

echo "[5/5] Creating start scripts ..."
# Windows start.bat
cat > "$DEPLOY/start.bat" << 'BAT'
@echo off
title CW Finance Server
echo ========================================
echo   CW Finance - Starting...
echo ========================================
echo.
echo   Opening: http://localhost:3005
echo   Login  : admin / admin123
echo.
echo   Press Ctrl+C to stop server
echo ========================================
echo.
set "PATH=%~dp0node;%PATH%"
echo Starting server...
start http://localhost:3005
node server\bundle.cjs
pause
BAT

# macOS/Linux start.sh
cat > "$DEPLOY/start.sh" << 'SHELL'
#!/bin/bash
echo "========================================"
echo "  CW Finance - Starting..."
echo "========================================"
echo ""
echo "  URL: http://localhost:3005"
echo "  User: admin / admin123"
echo ""
echo "  Press Ctrl+C to stop"
echo "========================================"
echo ""
cd "$(dirname "$0")"
node server/bundle.cjs
SHELL
chmod +x "$DEPLOY/start.sh"
echo "      OK"
echo ""

echo "========================================"
echo "  BUILD SUCCESS"
echo "========================================"
echo ""
echo "  Output : $ROOT/$DEPLOY/"
echo "  Start  : $ROOT/$DEPLOY/start.bat (Windows)"
echo "  Start  : $ROOT/$DEPLOY/start.sh (macOS/Linux)"
echo ""
echo "  Next steps:"
echo "  1. Copy '$DEPLOY' folder to target server"
echo "  2. Double-click start.bat or run ./start.sh"
echo "  3. Open http://localhost:3005"
echo "  4. Login: admin / admin123"
echo ""
