@echo off
setlocal enabledelayedexpansion

echo.
echo ========================================
echo   CW Finance - Build Deployment Package
echo ========================================
echo.

set "NODE_VER=20.18.3"
set "NODE_URL=https://nodejs.org/dist/v%NODE_VER%/node-v%NODE_VER%-win-x64.zip"
set "NODE_ZIP=node-v%NODE_VER%-win-x64.zip"
set "DEPLOY=deploy-final"

cd /d "%~dp0.."
set "PROJ_DIR=%CD%"

echo [1/6] Building frontend (Vite) ...
cd /d "%PROJ_DIR%\client"
call npx vite build
if errorlevel 1 (
    echo ERROR: Frontend build failed
    pause
    exit /b 1
)
echo       OK
echo.

echo [2/6] Building backend bundle (esbuild) ...
cd /d "%PROJ_DIR%\server"
call node scripts/buildBundle.mjs
if errorlevel 1 (
    echo ERROR: Backend bundle failed
    pause
    exit /b 1
)
echo       OK
echo.

echo [3/6] Preparing deploy directory ...
cd /d "%PROJ_DIR%"
if exist "%DEPLOY%" rmdir /s /q "%DEPLOY%"
mkdir "%DEPLOY%"
mkdir "%DEPLOY%\client"
mkdir "%DEPLOY%\server"
mkdir "%DEPLOY%\data"
mkdir "%DEPLOY%\uploads"
echo       OK
echo.

echo [4/6] Downloading Node.js %NODE_VER% ...
if not exist "%PROJ_DIR%\%NODE_ZIP%" (
    powershell -Command "Invoke-WebRequest -Uri '%NODE_URL%' -OutFile '%PROJ_DIR%\%NODE_ZIP%'"
    if errorlevel 1 (
        echo ERROR: Node.js download failed
        echo Please download manually: %NODE_URL%
        pause
        exit /b 1
    )
)
echo       Extracting ...
if exist "%PROJ_DIR%\node-v%NODE_VER%-win-x64" rmdir /s /q "%PROJ_DIR%\node-v%NODE_VER%-win-x64"
powershell -Command "Expand-Archive -Path '%PROJ_DIR%\%NODE_ZIP%' -DestinationPath '%PROJ_DIR%' -Force"
if exist "%DEPLOY%\node" rmdir /s /q "%DEPLOY%\node"
move "%PROJ_DIR%\node-v%NODE_VER%-win-x64" "%DEPLOY%\node" >nul
echo       OK
echo.

echo [5/6] Installing production dependencies ...
echo       (using portable Node.js to match better-sqlite3 binary)
cd /d "%PROJ_DIR%\server"
copy /y package.json "%PROJ_DIR%\%DEPLOY%\server\package.json" >nul
copy /y package-lock.json "%PROJ_DIR%\%DEPLOY%\server\package-lock.json" >nul 2>nul
cd /d "%PROJ_DIR%\%DEPLOY%\server"

echo       Portable Node version:
"%PROJ_DIR%\%DEPLOY%\node\node.exe" -v

echo       Clearing better-sqlite3 cache ...
rmdir /s /q "%USERPROFILE%\.npm\_cacache" 2>nul
rmdir /s /q "%USERPROFILE%\.npm\_prebuild-install-cache" 2>nul

echo       Installing dependencies with portable Node ...
set "PATH=%PROJ_DIR%\%DEPLOY%\node;%PATH%"
set "npm_config_target_arch=x64"
set "npm_config_target_platform=win32"
call npm install --omit=dev
if errorlevel 1 (
    echo ERROR: npm install failed
    pause
    exit /b 1
)

if not exist "node_modules\better-sqlite3\build\Release\better_sqlite3.node" (
    echo ERROR: better-sqlite3 binary not found!
    pause
    exit /b 1
)
"%PROJ_DIR%\%DEPLOY%\node\node.exe" -e "var m = require('./node_modules/better-sqlite3'); m(':memory:').close(); console.log('       ABI verified: ' + process.versions.modules)"
echo       OK (better-sqlite3 binary verified)
echo.

echo [6/6] Copying files ...
cd /d "%PROJ_DIR%"

copy /y "server\dist\bundle.cjs" "%DEPLOY%\server\" >nul

copy /y "server\src\db\schema.sql" "%DEPLOY%\server\schema.sql" >nul

echo # Deployment .env - generated by build script > "%DEPLOY%\server\.env"
echo # JWT Secret - change to a strong random string in production >> "%DEPLOY%\server\.env"
echo JWT_SECRET=your-secret-key-change-this-in-production >> "%DEPLOY%\server\.env"
echo       Created deployment .env file

xcopy "client\dist\*" "%DEPLOY%\client\dist\" /E /I /Y >nul

if exist "data\finance.db" (
    echo       Copying current database ...
    copy /y "data\finance.db" "%DEPLOY%\data\finance.db" >nul
    echo       Database copied: data\finance.db
) else (
    echo       No existing database found, will create new on first run
)

echo       OK
echo.

echo Creating start.bat ...
(
echo @echo off
echo title CW Finance Server
echo echo ========================================
echo echo   CW Finance - Starting...
echo echo ========================================
echo echo.
echo echo   Opening: http://localhost:3005
echo echo   Login  : admin / admin123
echo echo.
echo echo   Press Ctrl+C to stop server
echo echo ========================================
echo echo.
echo set "PATH=%%~dp0node;%%PATH%%"
echo echo Starting server...
echo start http://localhost:3005
echo node server\bundle.cjs
echo pause
) > "%DEPLOY%\start.bat"

echo.
echo ========================================
echo   BUILD SUCCESS
echo ========================================
echo.
echo   Output : %DEPLOY%\
echo   Node.js: v%NODE_VER% (portable)
echo   Start  : %DEPLOY%\start.bat
echo.
echo   Next steps:
echo   1. Copy '%DEPLOY%' folder to target server
echo   2. Double-click start.bat
echo   3. Open http://localhost:3005
echo   4. Login: admin / admin123
echo.
pause
